#! /bin/sh

pulseaudio --start
sxhkd &
albert &
nm-applet &
sh $HOME/.config/polybar/launch.sh

bspc monitor DVI-D-0 -d 1 2
bspc monitor DP-0 -d 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap 5

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a albert focus=on
bspc rule -a firefox desktop="^1" split_dir=north split_ratio=0.75
bspc rule -a kitty desktop="^1" split_dir=south split_ratio=0.75
bspc rule -a discord desktop="^2" split_dir=north split_ratio=0.75
bspc rule -a Deluge desktop="^2" split_dir=south split_ratio=0.75
bspc rule -a firefox desktop="^4" split_dir=east split_ratio=0.5