#! /bin/sh

mode="multiple"

sxhkd &
nm-applet &
sh $HOME/.config/polybar/launch.sh

if [ "$mode" = "multiple" ]; then
	bspc monitor eDP-1 -d 1 2
	bspc monitor DP-1 -d 3 4 5 6 7
	bspc monitor HDMI-2 -d 8 9 10
else
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7
	bspc monitor HDMI-2 -d 8 9 10
fi

bspc config border_width 1
bspc config window_gap 5

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a '*:*:Picture in picture' state=floating
bspc rule -a kitty split_ratio=0.75 split_dir=south