#! /bin/sh
source ~/.config/bspwm/monitorMode
echo $MONITOR_MODE
mode=$MONITOR_MODE

xrandr --auto

if [ "$mode" = "multiple" ]; then
	xrandr --output HDMI-2 --primary
	xrandr --output eDP-1 --rotate left --right-of HDMI-2

	bspc monitor HDMI-2 -d 1 2 3 4 5 6 7
  bspc monitor eDP-1 -d 8 9 10
	bspc config -m HDMI-2 right_padding 0
	bspc config -m HDMI-2 bottom_padding 30
else
	xrandr --output HDMI-2 --off
	xrandr --output eDP-1 --primary
	xrandr --output eDP-1 --rotate normal

	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
	bspc config -m eDP-1 right_padding 0
	bspc config -m eDP-1 bottom_padding 0

	killall brave
	killall steam
	killall kitty
	killall code-oss
fi

bspc config border_width 1
bspc config window_gap 5

bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a '*:*:Picture in picture' state=floating
bspc rule -a kitty split_ratio=0.75 split_dir=south

sxhkd &
nm-applet &
sh $HOME/.config/polybar/launch.sh