#!/bin/sh

mode="multiple"
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ "$mode" = "multiple" ]; then
	xrandr --output eDP-1 --left-of DP-2 --output DP-2 --primary --output HDMI-2 --rotate left --right-of DP-2
else
	xrandr --output eDP-1 --primary --output HDMI-2 --right-of eDP-1
	#xrandr --output HDMI-2 --primary --output eDP-1 --left-of HDMI-2
fi

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
mpd
exec bspwm