#!/bin/bash

start=`date +%s`

rclone -P sync ~/Backups googleDrive:Backups
echo "-----"
rclone -P sync ~/Documents googleDrive:Documents
echo "-----"
rclone -P sync ~/Music googleDrive:Music
echo "-----"
rclone -P sync ~/Pictures --exclude .images/ googleDrive:Pictures
echo "-----"
rclone -P sync ~/Programming --exclude "Active Projects/" googleDrive:Programming
echo "-----"
rclone -P sync ~/Videos googleDrive:Videos

notify-send "Backup has finished"

end=`date +%s`

readableseconds $((end-start))
