#!/bin/bash

start=`date +%s`

cd "/home/dedeco99/Music/toSort"

playlist="PL_OrlqKoK4aRt6sajvTSCneLlOjFxsV_j"

if [[ -n $1 ]]; then
    playlist="PL_OrlqKoK4aSvR-uUQqTQt7-zIrYxouo_"
fi

yt-dlp -x --audio-format best --audio-quality 0 https://www.youtube.com/playlist\?list\=$playlist --extractor-args "youtube:player-client=default,-tv_simply"

beet import -s .

rclone -P sync ~/Music/Music dedeco99-Pixel:Download/Music --disable PartialUploads --ftp-concurrency 1

notify-send "MusicDL has finished"

end=`date +%s`

readableseconds $((end-start))
