#!/bin/bash

start=`date +%s`

playlist="PL_OrlqKoK4aRt6sajvTSCneLlOjFxsV_j"

if [[ -n $2 ]]; then
    playlist="PL_OrlqKoK4aSvR-uUQqTQt7-zIrYxouo_"
fi

curl --header "Authorization: Bearer $1" https://ehub.rabbitsoftware.dev/api/youtube/playlist/$playlist?clearPlaylist=false

rm ~/Music/toSort/*

end=`date +%s`

readableseconds $((end-start))
