#! /bin/sh

mode=${1:-multiple};

echo $mode;

if [ $mode == "multiple" ]; then
	sed -i "4s/#//" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "5s/#//" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "8s/^#*/#/" ~/Programming/Projects/dotfiles/hypr/monitors.conf
else if [ $mode == "tv" ]; then
	sed -i "4s/^#*/#/" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "5s/^#*/#/" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "8s/#//" ~/Programming/Projects/dotfiles/hypr/monitors.conf
else
	sed -i "4s/^#*/#/" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "5s/^#*/#/" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "8s/#//" ~/Programming/Projects/dotfiles/hypr/monitors.conf
	sed -i "8s/1/2/" ~/Programming/Projects/dotfiles/hypr/monitors.conf
fi
