#!/bin/bash

start=`date +%s`

if [[ -f $1 ]]; then
    ffs "${1%.*}.mkv" -i "${1%.*}.srt" -o "${1%.*}.srt"
else
    for i in *.srt
		do ffs "${i%.*}.mkv" -i "${i%.*}.srt" -o "${i%.*}.srt"
	done
fi

notify-send "Subsync has finished"

end=`date +%s`

readableseconds $((end-start))
