#!/bin/sh

fileType=${1:-mp4};

read -s -p "Password: " password;

videoFolder="/home/dedeco99/Torrents";

cd $videoFolder;

function moveFiles
{
	for dir in */; do
		echo $dir;

		arrSplit=(${dir//.S0/ });
		hasSeason=${arrSplit[1]};
		newDir=${arrSplit[0]};
		finalDir=$dir;
		scpDir="Movies";
		isTV=true;

		if [ -z "$hasSeason" ]; then
			isTV=false;
		fi

		mp4s=$(ls -1 "$dir"/*.$fileType 2>/dev/null | wc -l);
		srts=$(ls -1 "$dir"/*.srt 2>/dev/null | wc -l);

		if [ ! $mp4s == $srts ]; then
			if [ -d "$dir/Subs" ]; then
				for file in $dir/*.$fileType; do
					subDir="$dir/Subs";

					filename=$(basename $file);
					filename="${filename//\.$fileType/}";

					if [ $isTV == true ]; then
						subDir="$dir/Subs/$filename";
					fi

					unset finalSub;
					
					for sub in $subDir/*; do
						if [[ $sub == *"_por"* ||  $sub == *"Portuguese"* ]]; then
							if [[ $sub != *"Br"* &&  $sub != *"br"* ]]; then
								finalSub=$sub;
							fi
						fi
						
						if [ -z "$finalSub" ]; then
							if [[ $sub == *"_por"* ||  $sub == *"Portuguese"* ]]; then
								finalSub=$sub;
							fi
						fi
					done

					mv "$finalSub" "$dir/$filename.srt";
				done
			fi
		fi
	done

	subliminal --opensubtitles dedeco99 "$password" download -l $1 -s .;

	for dir in */; do
		mp4s=$(ls -1 "$dir"/*.$fileType 2>/dev/null | wc -l);
		srts=$(ls -1 "$dir"/*.srt 2>/dev/null | wc -l);

		if [ $mp4s != 0 ] && [ $mp4s == $srts ]; then
			if [ $isTV == true ]; then
				finalDir="${newDir//\./ }";
				scpDir="TVShows";

				mv "$dir" "$finalDir";
			fi

			echo $finalDir;
		
			sshpass -p "$password" scp -r "$finalDir" dedeco99@192.168.1.238:/BigBoyWIP/$scpDir;
			
			rm -rf "$finalDir";
		fi
	done

	echo "Files moved";
}

moveFiles pt;

moveFiles pt-br;

