#!/bin/sh

fileType=${1:-mp4};

read -s -p "Password: " password;

downloadFolder="/home/dedeco99/Downloads/Torrents";
videoFolder="/home/dedeco99/Videos/Torrents";

torrents=$(deluge console 'info' --sort-reverse progress);

files=$(awk '{for(i=1;i<=NR;i+=3) if(NR==i && $2=="100%") print $3}' <<< $torrents);

for file in $files; do
	mv $downloadFolder/$file $videoFolder/$file;
done

cd $videoFolder;

function moveFiles
{
	for dir in */; do
		echo $dir;

		arrSplit=(${dir//.S0/ });
		hasSeason=${arrSplit[1]};
		newDir=${arrSplit[0]};
		finalDir=$dir;
		scpDir="Movies";
		isTV=true;

		if [ -z "$hasSeason" ]; then
			isTV=false;
		fi

		mp4s=$(ls -1 "$dir"/*.$fileType 2>/dev/null | wc -l);
		srts=$(ls -1 "$dir"/*.srt 2>/dev/null | wc -l);

		if [ ! $mp4s == $srts ]; then
			if [ -d "$dir/Subs" ]; then
				for file in $dir/*.$fileType; do
					subDir="$dir/Subs";

					filename=$(basename $file);
					filename="${filename//\.$fileType/}";

					if [ $isTV == true ]; then
						subDir="$dir/Subs/$filename";
					fi

					subs=$(ls $subDir | grep "Portuguese");

					if [ ! -z "$subs" ]; then
						subSplit=(${subs// / });
						finalSub=${subSplit[0]};

						for sub in $subs; do
							portugal=$(grep -w "$subDir/$sub" -e "tu");

							if [ ! -z "$portugal" ]; then
								finalSub=$sub;
							fi
						done
						
						mv "$subDir/$finalSub" "$dir/$filename.srt";
					fi
				done
			fi

			subliminal --opensubtitles dedeco99 "$password" download -l $1 -s "$dir";
		fi

		if [ $mp4s != 0 ] && [ $mp4s == $srts ]; then
			if [ $isTV == true ]; then
				finalDir="${newDir//\./ }";
				scpDir="TVShows";

				mv "$dir" "$finalDir";
			fi

			echo $finalDir;
		
			sshpass -p "$password" scp -r "$finalDir" dedeco99@192.168.1.238:/BigBoyWIP/$scpDir;
			
			rm -rf "$finalDir";
		fi
	done

	echo "Files moved";
}

moveFiles pt;

moveFiles pt-br;

