source ~/antigen.zsh

# Plugins
antigen use oh-my-zsh

# Bundle plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle command-not-found

# Load the theme.
#antigen theme agnoster
antigen theme bhilburn/powerlevel9k powerlevel9k

# POWERLEVEL9K_MODE="nerdfont-complete"
# POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0BC'
# POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0BA'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
# POWERLEVEL9K_PROMPT_ON_NEWLINE=true

# Tell Antigen that you're done.
antigen apply

# Aliases
alias update="yay -Syu && polybar-msg action \"#updates.hook.0\""
alias install="yay -S"
alias uninstall="yay -Rsn"
alias search="yay -Ss"
alias clean="yay -Yc"

alias eh-ssh="ssh ehub.rabbitsoftware.dev"
alias tp-ssh="ssh tipyfamily.com"

alias r-cd="cd ~/Programming/Projects/rodrigobot"
alias eh-cd="cd ~/Programming/Projects/entertainmenthub/server"
alias hk-cd="cd ~/Programming/Projects/housekeeper"
alias ch-cd="cd ~/Programming/Projects/chat"

alias t-cd="cd ~/Programming/Projects/tipy/server"
alias ta-cd="cd ~/Programming/Projects/tipy-agenda/server"

alias graph="git log --graph --abbrev-commit --decorate --format=format:'%C(bold yellow)%d%n %C(white)%<|(85,trunc)%s %C(bold green)%ad %C(dim white)%an' --date=format:'%d %b %Y %H:%M' --all"
alias stage="git add"
alias unstage="git reset"
alias discard="git checkout"
alias commit="git commit -m"
alias undo="git reset --soft HEAD~1"
